### ISSUE TITLE
creating IAM entities - need capabilities

### ISSUE THREAD

**Issue by aabes** [sparkleformation/sfn#102]
Seems that the CLI help supports passing in capabilities, but the create action does not pass those along to miasma, resulting in CF declaring bad request.

At least that's what I think is happening based on: https://github.com/sparkleformation/sfn/blob/master/lib/sfn/command/create.rb#L70

**Comment by chrisroberts** [comment]
Hi! You can enable this within your `.sfn` configuration file:

```ruby
Configuration.new do
  ...
  options do
    capabilities ['CAPABILITY_IAM']
  end
  ...
end
```

If you still have issues, please respond back and I'll re-open this issue. Cheers!

**Comment by aabes** [comment]
Thanks for quick reply !  and Sorry I should have put more context about how I'm using it:
 a) json configuration, which has:
  "processing":true,
  "capabilities": "CAPABILITY_IAM"

 b) I'm using sfn binary, not the knife integration.

I've tried many different options, and used debugger to insect stack around: ruby-2.2.1@chef/gems/miasma-0.2.38/lib/miasma/types/api.rb:122 , and saw no capabilities injected into the stack object.

Should I switch to using the ruby config file? the knife integration?

**Comment by chrisroberts** [comment]
So, the JSON data structure for configuration follows the same Ruby structure, so:

```ruby
Configuration.new do
  options do
    capabilities ['CAPABILITY_IAM']
  end
end
```

is defined in JSON as:

```json
{
  "options": {
    "capabilities": [
      "CAPABILITIES_IAM"
    ]
  }
}
```

As noted in IRC, the `--capabilities` flag looks to be an old artifact and is not tied to any functionality so I'll be removing that option.

**Comment by aabes** [comment]
Awesome !
