### ISSUE TITLE
API Error content not reported 

### ISSUE THREAD

**Issue by aabes** [sparkleformation/sfn#104]
Under an entertaining set of circumstances, CF returns an error message, even if a template is validated successfully. SFN CLI does not produce the content of the actual error, rather just:
`
ERROR: Miasma::Error::ApiError::RequestError: Bad Request
`

Looking at how miasma handles errors[1] - the error is made available to it, but content.get(*path) seems to fail to retrieve it (so this might be a miasma issue, but it causes usability problems with sfn)

[1] https://github.com/miasma-rb/miasma/blob/master/lib/miasma/error.rb#L58

**Comment by chrisroberts** [comment]
Was actually talking about this just last week. The knife plugin wraps the execute call to rescue out exceptions and provide the full error message/content. The direct sfn commands don't do this, and as such the error content is generally not visible. Command subclass should wrap up and provide this functionality.

**Comment by aabes** [comment]
I just realized that some of this might be my fault (or at least the way I invoke SFN). Seems that you get a choice between the stacktrace (DEBUG=1), or the error message in bogo-cli-0.1.32/lib/bogo-cli/setup.rb:55 )

`
            if(ENV['DEBUG'])
              $stderr.puts "ERROR: #{e.class}: #{e}\n#{e.backtrace.join("\n")}"
            else
              $stderr.puts "ERROR: #{e.class}: #{e.message}"
            end

`

**Comment by chrisroberts** [comment]
Yeah, but it _should_ be both. in debug mode it should be providing the `e.message` and not relying on the `to_s` for the full information.

**Comment by chrisroberts** [comment]
This is fixed in 2.0.4 and the `--debug` flag will properly provide you error + stack trace. Thanks for the report!
