### ISSUE TITLE
Using multiple template parameters

### ISSUE THREAD

**Issue by DHampe** [sparkleformation/sfn#105]
Hi all,

how can I use multiple parameters with sfn create --parameters.

Here is my command:
$ sfn create STACK -c aws.sfn --apply-stack BASESTACK --file out/cloudformationtemplate.json --parameters "Key1:Value1 Key2:Value2 Key3:Value3" --defaults --no-processing
[Sfn]: SparkleFormation: create
[Sfn]:   -> Name: STACK
[Sfn]: Stack runtime parameters:
[ERROR]: Value cannot be blank
[ERROR]: Value cannot be blank
[ERROR]: Value cannot be blank
[ERROR]: Value cannot be blank
[ERROR]: Value cannot be blank
[ERROR]: Value cannot be blank
[FATAL]: Failed to receive allowed parameter!

sfn only takes Key1:Value1 parameter and the others are ignored.

Thanks,
Dennis

**Comment by chrisroberts** [comment]
Hi! Parameter key/value pairs supplied on the CLI must be comma delimited: 

```
--parameters "Key1:Value1,Key2:Value2,Key3:Value3"
```

**Comment by DHampe** [comment]
Hi,

it is still not working:

sfn create STACK -c aws.sfn --apply-stack BASESTACK --file out/cloudformationtemplate.json --parameters "Key1:Value1,Key2:Value2,Key3:Value3" --defaults --no-processing
[Sfn]: SparkleFormation: create
[Sfn]:   -> Name: STACK
[Sfn]: Stack runtime parameters:
[ERROR]: Value cannot be blank
[ERROR]: Value cannot be blank
[ERROR]: Value cannot be blank
[ERROR]: Value cannot be blank
[ERROR]: Value cannot be blank
[ERROR]: Value cannot be blank
[FATAL]: Failed to receive allowed parameter!


I add the line  
  puts "config.get parameters #{config.get(:parameters)}"
 as debug output to file lib/sfn/command_module/stack.rb  and I get
config.get parameters {"Key1"=>"Value1,Key2:Value2,Key3:Value3"}

Only the first Key/value pair is accepted.

**Comment by chrisroberts** [comment]
Hi! Looks like there was an issue with the coerce block that formats the string into the hash structure that's causing this single value only problem. Fix is supplied in #109 and should be released later this afternoon. Will close this up once the release has been made. Thanks!

**Comment by chrisroberts** [comment]
This fix was released. Thanks for the report!
