### ISSUE TITLE
Support parameters from JSON or another sfn template

### ISSUE THREAD

**Issue by btisdall** [sparkleformation/sfn#13]
Hi Chris and thanks for more awesome work. It'd be really useful if sfn supported [parameters from a JSON file](http://blogs.aws.amazon.com/application-management/post/Tx1A23GYVMVFKFD/Passing-Parameters-to-CloudFormation-Stacks-with-the-AWS-CLI-and-Powershell) or another sfn template. Or is there a run-time reusability mechanism I'm missing?

**Comment by cwjohnston** [comment]
@btisdall when using the `create` and `update` commands, you can use `--apply-stack $STACKNAME` to collect the output values from $STACKNAME as the default values of matching parameters in the stack you are creating. Is this in line with what you're asking about?

**Comment by cwjohnston** [comment]
Alternately, if you want to define those parameters in one place to be reused across multiple templates, you can put them in a registry. See https://github.com/sparkleformation/sparkle_formation/blob/master/docs/building-blocks.md for more information on registries.

**Comment by btisdall** [comment]
@cwjohnston no, I'd like to achieve the opposite of reusing one set of parameter values across mutliple templates, I'm interested in using N sets of parameter values to create N different instances of a given stack.

**Comment by luckymike** [comment]
@btisdall it sounds like what you're after is nested stacks.

In your parent stack, you can have something like:

```ruby
parameters(:first_param) do
  type 'String'
end

parameters(:second_param) do
  type 'String'
end

n.times do
  nest!(:templates__my_template) 
end
```

In 'my_template.rb' you can reference those params:

```ruby
some_value ref!(:first_param)
another_value ref!(:second_param)
```

You could also just define those once in 'my_template.rb', and then do the `n.times` nest, as repeated parameters only need to be provided once with a nested template.

**Comment by luckymike** [comment]
I should add that Parameters file support is on the roadmap. :)

**Comment by btisdall** [comment]
Thanks everyone for the ideas, looks like nested stacks will do the job fine. Thanks @luckymike for the update too :)

**Comment by luckymike** [comment]
:+1: Keep on :sparkler:
