### ISSUE TITLE
planner yields false positives when comparing integers and integers as strings

### ISSUE THREAD

**Issue by cwjohnston** [sparkleformation/sfn#134]
When performing a stack update on a stack with a parameter for port number, accepting the default (existing value) causes the planner to indicate that the resource which references the value of that parameter will be modified, although no such modification takes place.

Specifically, the port parameter value is used to create an ElastiCache Redis cluster which would be replaced if the port were changed, but no such replacement occurs.

Appears to be related to the kind of integer vs integer as string comparison scenario addressed in #126

**Comment by chrisroberts** [comment]
Fixed in 2.1.4
