### ISSUE TITLE
Request: add a --region flag

### ISSUE THREAD

**Issue by gswallow** [sparkleformation/sfn#14]
Hi,

The only way I know of to change the AWS region I'm working in with the sfn tool is to specify a different config file.  I've looked into adding a --region flag, but I haven't cracked it yet, to submit a pull request.  Would this be a quick feature to add?

Thanks.

**Comment by chrisroberts** [comment]
Alright, new release has this properly fixed. You can specify credential overrides, which means you can override the environment:

```
$ sfn list --credentials "aws_region:us-west-1"
```

If you have any issues, please let me know. Thanks for the report!
