### ISSUE TITLE
aws_profile_name Not Working As Expected

### ISSUE THREAD

**Issue by maxmanders** [sparkleformation/sfn#150]
Firstly, let me make sure I understand the expected behaviour of using the `aws_profile_name` option in `.sfn`. I understand this is an option to [miasma-aws](https://github.com/miasma-rb/miasma-aws) rather than sfn, so perhaps I'm raising this issue in the wrong place. Please let me know if that's the case. The following shell output illustrates the issue I'm having.

```Bash
maxmanders@maxmanders-laptop:~/dev//sfn-development|master⚡
⇒  AWS_PROFILE=dev-full bundle exec sfn list
/Users/maxmanders/.rvm/gems/ruby-2.1.1@sfn-development/bin/ruby_executable_hooks:15: stack level too deep (SystemStackError)
maxmanders@maxmanders-laptop:~/dev//sfn-development|master⚡
⇒  env | grep -i aws
AWS_HOME=/Users/maxmanders/.aws
maxmanders@maxmanders-laptop:~/dev//sfn-development|master⚡
⇒  AWS_STS_ROLE_ARN=arn:aws:iam::XXXXXXXXXXXX:role/DevOpsFullAdmin bundle exec sfn list
Name                 Created              Updated              Status               Template Description
maxmanders@maxmanders-laptop:~/dev//sfn-development|master⚡
⇒  AWS_PROFILE=dev-full AWS_STS_ROLE_ARN=arn:aws:iam::XXXXXXXXXXXX:role/DevOpsFullAdmin bundle exec sfn list
/Users/maxmanders/.rvm/gems/ruby-2.1.1@sfn-development/bin/ruby_executable_hooks:15: stack level too deep (SystemStackError)
maxmanders@maxmanders-laptop:~/dev//sfn-development|master⚡
⇒  env | grep -i aws
AWS_HOME=/Users/maxmanders/.aws
```

Based on my `.sfn` file, if `AWS_PROFILE` is exported into the environment, `aws_profile_name` is called with the value of that variable. Subsequently, `aws_sts_role_arn` is called with the value of `AWS_STS_ROLE_ARN`, if that variable has been exported into the environment. I have assumed that if `aws_profile_name` is called, the associated AWS profile defined in `~/.aws/config` would be inspected to retrieve the `role_arn` config property, rendering `AWS_STS_ROLE_ARN` redundant.  However, the excerpt above seems to show that `aws_profile_name` is generating an error, and that `AWS_STS_ROLE_ARN` is required when assuming an IAM role.  A redacted version of the profile I'm using is shown below.

```Bash
maxmanders@maxmanders-laptop:~/dev/sfn-development|master⚡
⇒  grep -A5 dev-full ~/.aws/config
[profile dev-full]
region = us-east-1
output = json
role_arn = arn:aws:iam::XXXXXXXXXXXX:role/DevOpsFullAdmin
source_profile = base 
mfa_serial = arn:aws:iam::YYYYYYYYYYYY:mfa/max.manders
```

The relevant section of `.sfn` is

```Ruby
    if ENV['AWS_ACCESS_KEY_ID']
      aws_access_key_id ENV['AWS_ACCESS_KEY_ID']
      aws_secret_access_key ENV['AWS_SECRET_ACCESS_KEY']
      aws_sts_session_token ENV['AWS_SESSION_TOKEN']
    else
      aws_profile_name ENV['AWS_PROFILE'] || 'default'
    end

    aws_sts_role_arn ENV['AWS_STS_ROLE_ARN'] if ENV['AWS_STS_ROLE_ARN']

```

Please let me know if I can do more to provide examples or context, or point me in the right direction to further diagnose this problem!

Cheers,
Max

**Comment by chrisroberts** [comment]
Hi! This is a miasma-aws related issue, however sfn is the main vehicle to the library so it's fine here. I'll just create an issue there referencing this issue once something is identified. 

First thing first, what version of miasma-aws are you currently using? The STS related stuff got a recent refactoring so I'd like to be sure you're using the latest. The error shows something is recursing until the stack dumps which is much less than ideal :neutral_face: 

On a side note, sfn has a builtin callback for MFA on AWS. It may not be applicable depending on your setup, but just be aware that it is there if you don't want to use a wrapper.

Let me know about the version, I'll get it reproducing locally and get a fix identified. Thanks!

**Comment by maxmanders** [comment]
Wow - that's the fastest response I've ever seen to an issue I've raised!

```Bash
```

**Comment by chrisroberts** [comment]
@maxmanders Thanks for the extra information. Looks like it's an issue around the role arn being provided via the config file, which causes the STS instance internally to set the role arn again, which causes it to create a new STS instance, and on and on. For now, removing the role_arn from the config will "fix" the problem. I'll be pushing out an update to miasma-aws that has the fix in it shortly. Thanks for the report!

**Comment by maxmanders** [comment]
*falls off chair* fantastic service Chris, very much appreciated!

**Comment by maxmanders** [comment]
Hey @chrisroberts - I noticed you'd merged a fix into miasma-rb/miasma-aws in miasma-rb/miasma-aws#36.  Should I be loading the develop branch into my Gemfile to test this, or is the merge just pending release?

**Comment by chrisroberts** [comment]
Hiya @maxmanders. It is just pending release. I'm getting a handful of things wrapped up and will be getting them shipped today. You can point your bundle to the repo if you need it immediately, but it will be getting rolled out today.

**Comment by maxmanders** [comment]
Wonderful!

**Comment by chrisroberts** [comment]
Fixes on miasma-aws are released. Let me know if you have any problems. Thanks!
