### ISSUE TITLE
Feature Request: Stack tags modification on stack update

### ISSUE THREAD

**Issue by jimcroft** [sparkleformation/sfn#154]
AWS recently announced that stack tags, previously immutable, can now be modified during a stack update.

"Edit tags when updating stacks: Add, modify, or remove stack tags when you update your stack. Previously, you could not make changes to tags when updating your stack."

Ref: https://aws.amazon.com/about-aws/whats-new/2016/02/aws-cloudformation-adds-support-for-amazon-vpc-nat-gateway-amazon-ec2-container-registry-and-more/

Would be nice for sfn to support this.

**Comment by chrisroberts** [comment]
@jimcroft This has been implemented but it is an "opt-in" feature. #162 provides the reasoning for it being opt-in. This means you'll either need to include `--merge-api-options` on the CLI or add:

```ruby
merge_api_options true
```

to your configuration file if you want to have it "always on". Thanks!
