### ISSUE TITLE
The --file option doesn't seem to like paths beginning with ./

### ISSUE THREAD

**Issue by mconigliaro** [sparkleformation/sfn#155]
This fails:
   
    sfn print test -f ./sparkleformation/test.rb
    ERROR: SparkleFormation::Error::NotFound::Template: ["No template registered with requested name (./sparkleformation/test.rb)!"]

This works:

    sfn print test -f sparkleformation/test.rb

**Comment by chrisroberts** [comment]
Fixed and staged for release. Thanks!
