### ISSUE TITLE
Provide a `--plan-only` or `--no` option to `update` for plan-only output.

### ISSUE THREAD

**Issue by grahamc** [sparkleformation/sfn#156]
I want to run sfn in a CD environment. I would like to have two stages: one outputs the planned updates, then a manual approval (in my CD system) to actually run the update. This would look like

```
# Stage 1
$ sfn update --plan-only --no-interactive-parameters --no-processing --file ./cloudformation.json -m "MyParam:MyValue" MyStack
```

 manual approval in the UI

```
# Stage 2
$ sfn update --yes --no-interactive-parameters --no-processing --file ./cloudformation.json -m "MyParam:MyValue" MyStack
```

**Comment by chrisroberts** [comment]
I have added the `--plan-only` option via #158 which will remain in the future. However, I will be looking at adding in an explicit `plan` command and extracting the implementation from the `update` command. The `update` command will still automatically invoke the planner, but this will provide a more direct approach for plan generation only.

For now, the option is enough. Thanks!

**Comment by chrisroberts** [comment]
Staged for release so closing this up. Thanks!
