### ISSUE TITLE
Stack update when parameter NoEcho == true

### ISSUE THREAD

**Issue by jimcroft** [sparkleformation/sfn#164]
When creating stacks containing RDS instances we use a parameter to set the master users password. The parameter is flagged NoEcho == true.

eg.

```
rds_master_password do
  type 'String'
  description 'RDS master user password'
  no_echo true
end
```

This means fetching the parameter value from the running stack always returns '****'. During an sfn update that value will be used as the default/previous value and either reset the password (or in the case of RDS cause the stack update to fail as that password is invalid for RDS).

I can work around it as I know the password(s) but others running updates might not so this is an issue (as in either case we could accidently reset the password during the update).

Where NoEcho is set for parameters (always in my experience, for passwords), sfn should default to UsePreviousValue for updates.

Ref: http://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_Parameter.html

**Comment by jimcroft** [comment]
Related...

It would be a nice to have if sfn could honour the NoEcho flag when interactively entering these param values.

ie. instead of...

```[Sfn]: Rds Master Password []: mysupersecretpassword```

it would echo '*' chars as we type

```[Sfn]: Rds Master Password []: ***********```

**Comment by chrisroberts** [comment]
:+1:

**Comment by chrisroberts** [comment]
Looking at implementing this within a larger scope to handle sensitive information display of inputs as well as outputs from the stack.

**Comment by runningman84** [comment]
any news here? I have just messed up my stacks by accepting the defaults (******) and thought it would not change the database password....

**Comment by chrisroberts** [comment]
Closing as this was fixed in underlying support libraries. Cheers!
