### ISSUE TITLE
Allowed_values in compile time parameters

### ISSUE THREAD

**Issue by rabidscorpio** [sparkleformation/sfn#165]
It would be really nice if we could specify allowed_values in the compile time parameters. This would prevent typos or bad values from being passed in to the stack.

**Comment by chrisroberts** [comment]
:+1:

**Comment by chrisroberts** [comment]
This has been added in 3.0.6. Also includes support for: `min_value`, `max_value`, `min_length`, `max_length`, and `allowed_pattern`.
