### ISSUE TITLE
Empty string parameters

### ISSUE THREAD

**Issue by jimcroft** [sparkleformation/sfn#169]
Unless AllowedValues, AllowedPattern or MinLength settings prohibit it, sfn should allow empty string parameters to be used when creating or updating stacks.

We allow empty strings for things like SnapshotIdentifier in AWS::RDS::DBCluster or SnapshotArns/SnapshotName in AWS::ElastiCache::CacheCluster to bring up new services from existing snapshots. If they're blank the new services come up empty. We use conditions in the template to determine the behaviour. Sfn currently doesn't allow this.

**Comment by jimcroft** [comment]
Note: To make it clearer, we allow the parameters for SnapshotIdentifier, etc. to be blank, not the actual resource property value. The templates will then do something like:

```
parameters do
    snapshot_identifier do
        type 'String'
    end
end

conditions do
    use_existing_snapshot not!(equals!(ref!(:snapshot_identifier), '')
end

resources(:db) do
    type 'AWS::RDS::DBInstance'
    properties do
        snapshot_identifier if!(:use_existing_snapshot, ref!(:snapshot_identifier), no_value!)
    end
end
```

**Comment by chrisroberts** [comment]
Hi! Instead of using an empty string check, I would suggest using an explicit string. For example:

```ruby
parameters.snapshot_identifier do
  type 'String'
  default 'none'
end

conditions.use_existing_snapshot not!(equals!(ref!(:snapshot_identifier, 'none')))
```

Empty values for parameters are almost always wrong, which is why sfn requires a value provided (unless side stepped by the allow_* options).
