### ISSUE TITLE
stop preloading all gems

### ISSUE THREAD

**Issue by grosser** [sparkleformation/sfn#170]
just took our `sfn print` from 4s to 1s by making sfn stop doing the bundler/require ... I know it's convenient, but ideally it should not do that ... or put the `require 'bundler/require' if defined?(Bundler)` in the generated `.sfn` so it can be removed ... ideally it would always create a `Gemfile` since running sfn without a Gemfile is just gambling ...

monkeypath for Gemfile ... or add `require: false` to every gem ...
```Ruby
def Bundler.require;end # make sfn fast by not preloading all gems
```

@chrisroberts

**Comment by chrisroberts** [comment]
Can you provide an example bundle that is causing such a long load time?

**Comment by grosser** [comment]
```
gem 'aws-sdk', '~> 2'
gem 'sfn'
gem 'sparkle_formation', '~> 2.0'
gem 'rubocop'
gem 'rake', '~> 11.0'
gem 'capistrano'
gem 'highline'
gem 'parallel'
gem 'chef'
gem 'pry'
gem 'awesome_print'
gem 'knife-update-from-file'
```

**Comment by chrisroberts** [comment]
Using the provided bundle I was averaging about 2 seconds to run `bundle exec sfn --help`. Of the gems in the bundle, `chef` was the heaviest and easily visible by disabling its require. I don't want to remove the `Bundler.require` feature, but I also don't want the local bundle to adversely affect startup time. I found a good middle ground in #171 by _only_ auto-requiring gems defined within the `:sfn` group. Retains desired functionality and removes unintended startup slowdowns.

**Comment by grosser** [comment]
thx, that should take care of it / make it opt-in

**Comment by chrisroberts** [comment]
2.2 include support for the `:sfn` group which will restrict loading to only gems within that group. This will become the default behavior in 3.0.
