### ISSUE TITLE
Configuration option to select all "current/expected"

### ISSUE THREAD

**Issue by cixelsyd** [sparkleformation/sfn#177]
Currently, if I execute sfn via some type of job scheduler or orchestration engine, and I update input parameters, the job will fail while it waits on input "use current value or expected value for xxx".  I would like to have the ability to simply add something like "--current" or "--expected" to the configuration/CLI so that I can tell sfn to simply use all expected values or use all current values.

I'm currently running the sfn update job with both "--yes" and "-d" but they do not help in this situation.

**Comment by luckymike** [comment]
@cixelsyd have you tried the command with `--defaults` The current parameter values should be set as defaults for the update.

**Comment by luckymike** [comment]
Scratch that, I missed that you tried -d.

**Comment by luckymike** [comment]
@cixelsyd is your hope here that a `--current` or `--expected` would allow the stack update to run but maintain an externally adjusted (i.e. not via sfn/CFN update) value?

**Comment by chrisroberts** [comment]
The underlying cause of the prompts is resource modifications happening outside of the orchestration API and `sfn` not knowing what is assumed to be "correct". Ideally, the best solution is not modifying resources outside the orchestration API. However, that restriction can be difficult/impossible to impose  in practice. So, :+1: on adding options to control it, but the control will be very brute force-ish. Either all prompts answered with "expected" or "current". 

Semi-related thing that I would like to update along with this is defining a proper "interactive" mode such that all user interactions will result in an immediate error when the mode is disabled.

- [ ] provide options for auto-answer of current/expected on update
- [ ] rename `interactive_parameters` to just `interactive` and provide alias
- [ ] force immediate exception on all UI interactions when not in interactive mode

**Comment by cixelsyd** [comment]
Chris, you are correct: updating things outside of sparkleformation is
absolutely an anti-pattern; however, it seems like some edge cases could
lead one down that path occasionally.  I believe that I made it to that
place by adding an input parameter "primary_dns" to existing templates,
which then triggered an sfn message stating "

Parameter: PrimaryDns. Current value: . Expected value: <my desired value>"

The --expected/--current options that I am suggesting are just like a
sledgehammer, but would certainly permit me to very easily say "expected"
and continue to let my job-runner execute these template changes for me.

On Wed, Mar 30, 2016 at 3:28 PM, Chris Roberts <notifications@github.com>
wrote:

> The underlying cause of the prompts is resource modifications happening
> outside of the orchestration API and sfn not knowing what is assumed to
> be "correct". Ideally, the best solution is not modifying resources outside
> the orchestration API. However, that restriction can be
> difficult/impossible to impose in practice. So, [image: :+1:] on adding
> options to control it, but the control will be very brute force-ish. Either
> all prompts answered with "expected" or "current".
>
> Semi-related thing that I would like to update along with this is defining
> a proper "interactive" mode such that all user interactions will result in
> an immediate error when the mode is disabled.
>
>    - provide options for auto-answer of current/expected on update
>    - rename interactive_parameters to just interactive and provide alias
>    - force immediate exception on all UI interactions when not in
>    interactive mode
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/sparkleformation/sfn/issues/177#issuecomment-203595535>
>



-- 
http://linkedin.com/in/cixelsydego

(508) 372-0005 (cell)

**Comment by chrisroberts** [comment]
This functionality is now available within the 3.0.6 release using the `--parameter-validation` flag.

* `--parameter-validation none` - do not check parameters
* `--parameter-validation current` - use currently set value
* `--parameter-validation expected` - use expected value
