### ISSUE TITLE
Use S3 bucket for non-nested stack launches and updates

### ISSUE THREAD

**Issue by jimcroft** [sparkleformation/sfn#179]
I think related to https://github.com/sparkleformation/sparkle_formation/issues/166

Would be good if sfn supported uploading templates to S3 even when not using nesting. Templates can grow fairly large, and even though that probably shouts out for refactoring there are occasionally reasons that's not possible (or at least not possible now/quickly).

**Comment by chrisroberts** [comment]
Available via `--upload-root-template` flag in v3.0. Thanks!
