### ISSUE TITLE
sfn create crashes unless option is provided

### ISSUE THREAD

**Issue by johndkraft** [sparkleformation/sfn#18]
Hi!

Unless I'm missing something (and I must be.. I can't be the first person to do this) It seems that "sfn create" invocations exit with "ERROR: TypeError: can't dup NilClass" unless at least one option is provided in .sfn

lib/sfb/command/create.rb:55`             config[:options].dup.merge(`

In pry, I find that `config[:options]` is nil unless options were provided via config file or with -O

Thanks!

**Comment by chrisroberts** [comment]
Confirmed and fix identified in #19. Will close this once released. Thanks for the report and locating where the issue was originating!

**Comment by johndkraft** [comment]
Wow, I haven't even finished my cup of coffee.  Thanks!

**Comment by chrisroberts** [comment]
Fix released. Thanks!
