### ISSUE TITLE
Help for certain subcommands does not work in Bundler context

### ISSUE THREAD

**Issue by mfischer-zd** [sparkleformation/sfn#214]
When running `sfn` in a Bundler context (Bundler 1.12.4), supplying the `-h` option causes Bundler to print its man page, instead of showing the `sfn` subcommand's help text.

For example, `bundle exec sfn print -h` and `bundle exec sfn conf -h` work fine, but `bundle exec sfn create -h` and `bundle exec sfn update -h` does not.    The pattern I'm detecting (but cannot confirm) is that commands that have required arguments are failing.

**Comment by chrisroberts** [comment]
Hi! This is a bug in bundler, originally seen here:

https://github.com/bundler/bundler/pull/4487

and then again here: 

https://github.com/bundler/bundler/issues/4596

which is affecting your current version. Looks like upgrading bundler should stop it from intercepting the help options.

If you still have problems, please let me know. Cheers!

**Comment by mfischer-zd** [comment]
Confirmed - updating to 1.12.5 resolved the problem.  Thanks!
