### ISSUE TITLE
Stack events in configured timezone

### ISSUE THREAD

**Issue by gservat** [sparkleformation/sfn#215]
CloudFormation returns stack events in UTC time, so it would be great if there was some way to configure what timezone to display them in (either in .sfn or fallback to local system time).

**Comment by chrisroberts** [comment]
Updated the modeling library to return local time when coercing date values instead of the UTC time received. Provided in miasma v0.3.8 release via commit: https://github.com/miasma-rb/miasma/commit/20f87c220680eb770b3896601a675f56524d092b
