### ISSUE TITLE
Activate --upload-root-template by default somewhere in the conf

### ISSUE THREAD

**Issue by Esya** [sparkleformation/sfn#216]
Hi,

We have a few quite heavy templates (They contain a lot of instances) that go over the AWS limit for the size of the JSON, and therefore use the `--upload-root-template` option.

To avoid having to pass it manually every time, I think it would be nice to have a setting in `.sfn` to turn it on by default. What do you think?

**Comment by chrisroberts** [comment]
Hi. You can enable it by default in the configuration using:

```ruby
Configuration.new do
  upload_root_template true
  ...
```

Cheers!
