### ISSUE TITLE
Specifying CAPABILITY_NAMED_IAM still results in InsufficientCapabilities error

### ISSUE THREAD

**Issue by rmontgomery429** [sparkleformation/sfn#225]
I have a local `.sfn` file that specifies `capabilities ['CAPABILITY_NAMED_IAM']` based on the template generated from the sfn command line tool. 

Upon deployment we still receive the "InsufficientCapabilities"  error:

`ERROR: Miasma::Error::ApiError::RequestError: Bad Request - InsufficientCapabilitiesException: Requires capabilities : [CAPABILITY_NAMED_IAM]`

We're using sfn 3.0.18.

Our config:

``` ruby
Configuration.new do
  apply_nesting 'deep'
  processing true

  upload_root_template true
  nesting_bucket '...'

  options do
    on_failure 'nothing'
    notification_topics []
    capabilities ['CAPABILITY_NAMED_IAM']
    tags do
      creator ENV['...']
    end
  end

  credentials do
    provider :aws
    aws_access_key_id ENV['...']
    aws_secret_access_key ENV['...']
    aws_region ENV['...']
    aws_bucket_region ENV['...']
  end
end
```

Any guidance is much appreciated.

**Comment by rmontgomery429** [comment]
Related: https://github.com/sparkleformation/sfn/issues/102

**Comment by chrisroberts** [comment]
Hi! That error is generally a result of the user credentials being used not having the correct permissions assigned to enable the requested capability (`CAPABILITY_NAMED_IAM` in this case).

**Comment by rmontgomery429** [comment]
@chrisroberts ... dude. Thanks. We're going to look into that and see if that resolves this. I'll have an answer in some form or another here in a bit. I really appreciate it.

**Comment by rmontgomery429** [comment]
We're still seeing the issue with AdministratorAccess. If it is helpful to know we also recently upgraded. 

```diff
-gem 'sfn', '~> 2.2.0'
+gem 'sfn', '~> 3.0.18'
```

**Comment by rmontgomery429** [comment]
We also seem to notice that this occurs while updating a stack but not when creating a stack.

**Comment by chrisroberts** [comment]
In your `.sfn` configuration file, toss in `merge_api_options` and see if that fixes things up:

```ruby
Configuration.new do
  ...
  merge_api_options true
  ...
end
```

**Comment by chrisroberts** [comment]
@rmontgomery429 Hi! Did the configuration modification in the last comment get your issue sorted out?

**Comment by rmontgomery429** [comment]
@chrisroberts I'm not sure exactly. It was resolved but looking at our `.sfn` file, I don't see that in there now. It may have "resolved itself" somehow unfortunately. I wish had a more concrete answer. Sorry.

**Comment by chrisroberts** [comment]
Closing this up as it seems to have self-resolved. Please open a new issue if you experience it again. Cheers!

**Comment by slyness** [comment]
I just actually ran into this issue. Previously to today the issue was not showing up in past stack events. It crept in there today out of the blue. However, adding `merge_api_options true` to my .sfn file resolved it. 

```
sparkle_formation 3.0.10
sfn 3.0.20 and 18 (during test)
```

I'm not sure this warrants re-opening the issue but I wanted to document my scenario.

**Comment by cixelsyd** [comment]
Just for anyone who lands here via Google (top hit!), adding   `merge_api_options true` as Chris described above, along with `capabilities ['CAPABILITY_NAMED_IAM']` does resolve the issue for me.
