### ISSUE TITLE
Support yaml output as well as json

### ISSUE THREAD

**Issue by rabidscorpio** [sparkleformation/sfn#227]
With the new yaml template support (https://aws.amazon.com/about-aws/whats-new/2016/09/aws-cloudformation-introduces-yaml-template-support-and-cross-stack-references/), it would be nice to be able to `print` or `--print-only` and get yaml output as well as json since it's so much easier to read.

**Comment by chrisroberts** [comment]
Personally, serialization is serialization and what's easier to read is really just a matter of preference (as _I_ think JSON is much easier to read than YAML). Currently serialization format is dictated by the provider in use, but I don't have any issue with including a switch to specify a different format. I'll look to add in the option to the next release.
