### ISSUE TITLE
Template not found if provider not set.

### ISSUE THREAD

**Issue by luckymike** [sparkleformation/sfn#228]
See discussion here: https://github.com/reverseskate/sparkleformation-workshops/issues/5

Setting the provider in `.sfn` explicitly resolved the error, so it seems like the default of `:aws` is not being set correctly in 3.x. 

So, if you get an error like: 

```
ERROR: SparkleFormation::Error::NotFound::Template: Failed to locate item named: `example`
```

Add `provider :aws` to the `credentials` block of `.sfn`

**Comment by wallnerryan** [comment]
@luckymike this doesnt work when using `provider: open_stack` I still get the `SparkleFormation::Error::NotFound::Template:` errors
