### ISSUE TITLE
create new parameter --silent

### ISSUE THREAD

**Issue by kabakakao** [sparkleformation/sfn#237]
Hello,
I would like to see a parameter like '--silent'.
So it would be possible to start the build of a stack (or delete or update), but does not wait for completion.
This wish is caused by a scenario, where the build of the stack took more than one hour, but my assume role token is expired. So the creation ends up with an Error-Code != 0.
Thanks in advance,
Stephan

**Comment by chrisroberts** [comment]
Hi! You can accomplish this by using the `--no-poll` option with the `create` or `update` commands.

Cheers!
