### ISSUE TITLE
Stack policy failing on conditional resources

### ISSUE THREAD

**Issue by cwhetung** [sparkleformation/sfn#238]
When a resource contains both a stack policy rule and a condition that evaluates to false such as:

```ruby
dynamic!(:some_resource, :my_resource) do
  condition 'FalseCondition'
  policy do
    deny '*'
  end
end
```

Then when the stack policy callback triggers it will fail with an error indication that the policy is referencing a non-existent resource:

`ERROR: Miasma::Error::ApiError::RequestError: Bad Request - ValidationError: Error validating stack policy: Unknown logical id 'LogicalResourceId/MyResource' in statement {} - stack policies can only be applied to logical ids referenced in the template`

N.B. If the condition evaluates to `true` there is no error, since the resource was created

**Comment by chrisroberts** [comment]
Fix for this applied via #240
