### ISSUE TITLE
ability to specify SSL options?

### ISSUE THREAD

**Issue by rlwinter** [sparkleformation/sfn#239]
Hi, the AWS linux ami I have to use does not seem to have SSL certificates and Certificate Authorities configured the way sfn expects. When I do a `sfn list` command with my initial configuration I get an error: 'SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed'. Is there any way to specify the SSL key, certificate and CA files? along with 'ssl debug = true' and 'ssl noverify' options?

**Comment by chrisroberts** [comment]
Determining the root cause of why the verification is failing would be ideal. There currently isn't any way to configure the ssl context. If you _really_ want to set noverify, you can just disable it globally by putting this at the top of your `.sfn` configuration file:

```ruby
require 'openssl'
::OpenSSL::SSL::VERIFY_PEER = ::OpenSSL::SSL::VERIFY_NONE
...
```

Cheers!
