### ISSUE TITLE
sfn cli stops althogh miasma does a retry

### ISSUE THREAD

**Issue by kabakakao** [sparkleformation/sfn#256]
When there is a connection Problem to Cloudformation, miasma will retry the communication:

`[WARN]: Task failed (Miasma::Error::ApiError::RequestError: Bad Request) - Retry in 5 seconds [Attempt 1/20]`

But sfn stops polling:
```
[Sfn]: SparkleFormation: create
[Sfn]:   -> Name: PREPROD-LOGSTASH
[WARN]: Task failed (Miasma::Error::ApiError::RequestError: Bad Request) - Retry in 5 seconds [Attempt 1/20]
[Sfn]: Stack runtime parameters:
[Sfn]: Events for Stack: PREPROD-LOGSTASH
```

**Comment by chrisroberts** [comment]
This is working as expected in the current release. Please let me know if you are still encountering issues.
