### ISSUE TITLE
apply_stacks! is overwriting remote stack parameters and not detecting parameter updates

### ISSUE THREAD

**Issue by cwhetung** [sparkleformation/sfn#262]
When a stack is being updated, and its parameters are modified VIA an applied stack here: https://github.com/sparkleformation/sfn/blob/develop/lib/sfn/command/update.rb#L85

The `apply_stack!` modifies the API stack's parameters as well, this seems to cause the `UsePreviousValue` assignment [here](https://github.com/miasma-rb/miasma-aws/blob/b46ece7cbfb4d525d097d3ed2c6ae303f7bb9cd3/lib/miasma/contrib/aws/orchestration.rb#L161) to evaluate to `true`.

The end consequence seems to be that the API call to `UpdateStack`  doesn't actually contain any changes because `UsePreviousValue` is `true` and the actual new applied value was removed.

**Comment by chrisroberts** [comment]
Fixed via #261 

Thanks for the report!
