### ISSUE TITLE
sfn update does not get --apply-stack values

### ISSUE THREAD

**Issue by ldesiqueira** [sparkleformation/sfn#263]
Hello,

When I attempt to inherit values from a stack on the command line using --apply-stack I am unsuccessful if I am updating the stack.

`sfn update POCLogstash --file logstash --apply-stack POCCloudwatchLogsS3Bucket --defaults`

results in

`[Sfn]: SparkleFormation: update
[Sfn]:   -> Name: POCLogstash Path: /Users/luis.desiqueira/code/jobvite-sparkles/sparkleformation/logstash.rb
[Sfn]: Stack runtime parameters: - template: POCLogstash
[Sfn]: Cloudwatch Logs Bucket:` 

Which is of course a prompt for the value.  I do not have a default for the value set at the parameters declaration portion of the receiving stack.  I have tested this with a default set and it still does not pass.  

In order to make sure I was not doing something incorrectly I tried the create case, and it successfully passed the parameter from one stack to the next.

`sfn create TestPOCLogstash --file logstash --apply-stack POCCloudwatchLogsS3Bucket --defaults     [ruby-2.3.1@sfn]`

Which results in...

`[Sfn]: SparkleFormation: create
[Sfn]:   -> Name: TestPOCLogstash
[Sfn]: Stack runtime parameters: - template: TestPOCLogstash
[Sfn]: Events for Stack: TestPOCLogstash
Time                      Resource Logical Id   Resource Status      Resource Status Reason
2017-06-19 23:09:55 UTC   TestPOCLogstash       CREATE_IN_PROGRESS   User Initiated
2017-06-19 23:10:05 UTC   LogstashIamRole            CREATE_IN_PROGRESS
2017-06-19 23:10:06 UTC   LogstashIamRole            CREATE_IN_PROGRESS   Resource creation Initiated
2017-06-19 23:10:09 UTC   LogstashEc2SecurityGroup   CREATE_IN_PROGRESS
2017-06-19 23:10:09 UTC   LogstashEc2SecurityGroup   CREATE_IN_PROGRESS   Resource creation Initiated`

This finishes gracefully

for note I am using exactly these gems during execution.

addressable (2.5.0, 2.4.0)
attribute_struct (0.4.2, 0.3.4)
aws-sdk (2.6.17)
aws-sdk-core (2.6.17)
aws-sdk-resources (2.6.17)
bigdecimal (1.2.8)
bogo (0.2.8, 0.2.4)
bogo-cli (0.2.12, 0.2.10, 0.2.8)
bogo-config (0.2.2)
bogo-ui (0.1.24, 0.1.20, 0.1.16)
bundler (1.14.5)
bundler-unload (1.0.2)
colored (1.2)
command_line_reporter (3.3.6)
did_you_mean (1.0.0)
diplomat (1.1.0, 1.0.0)
domain_name (0.5.20170223, 0.5.20161021, 0.5.20160826)
executable-hooks (1.3.2)
faraday (0.9.2)
gem-wrappers (1.2.7)
graph (2.8.2, 2.8.1)
hashdiff (0.2.3)
hashie (3.5.5, 3.4.6, 3.4.4)
http (1.0.4)
http-cookie (1.0.3, 1.0.2)
http-form_data (1.0.1)
http_parser.rb (0.6.0)
io-console (0.4.5)
jmespath (1.3.1)
json (1.8.3)
miasma (0.3.2)
miasma-aws (0.3.6, 0.3.4)
miasma-azure (0.1.4)
miasma-google (0.1.0)
miasma-open-stack (0.1.4)
miasma-rackspace (0.1.2)
miasma-terraform (0.1.2)
mime-types (3.1)
mime-types-data (3.2016.0521)
minitest (5.8.3)
multi_json (1.12.1)
multi_xml (0.6.0, 0.5.5)
multipart-post (2.0.0)
net-ssh (4.1.0, 3.2.0)
net-telnet (0.1.1)
paint (2.0.0, 1.0.1)
power_assert (0.2.6)
psych (2.0.17)
public_suffix (2.0.5)
rake (10.4.2)
rdoc (4.2.1)
ruby-beautify (0.97.4)
rubygems-bundler (1.4.4)
rvm (1.11.3.9)
sfn (3.0.24, 3.0.22, 3.0.20, 3.0.18)
slop (3.6.0)
sparkle_formation (3.0.22, 3.0.14, 3.0.10)
test-unit (3.1.5)
unf (0.1.4)
unf_ext (0.0.7.2)
xml-simple (1.1.5)

**Comment by chrisroberts** [comment]
I believe this has been resolved in the latest release. Please let me know if you are still experiencing this behavior. Thanks!

**Comment by ldesiqueira** [comment]
It is resolved just checked thank you!!

**Comment by chrisroberts** [comment]
Fantastic. Thank you for the confirmation!
