### ISSUE TITLE
SFN Validate fails when it shouldn't for nested templates

### ISSUE THREAD

**Issue by pieter-vanisacker** [sparkleformation/sfn#272]
While validating stacks it seems like SFN provides the stack as template body to the AWS CloudFormation API.
When uploading in such a way there's a limit of 51200 bytes for a template.
This happens for the root stack and for the nested stacks.

But for nested stacks there's a much higher character limit: 460800 bytes.
See: https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_ValidateTemplate.html

https://github.com/sparkleformation/sfn/blob/develop/lib/sfn/command/validate.rb would probably need to be fixed so that it recognizes uploading nested stacks. And validates these using a template url parameter.

```
$ sfn -v
sfn - SparkleFormation CLI - [Version: 3.0.22]
```

**Comment by jimcroft** [comment]
IIRC you can add `upload_root_template true` to your .sfn config file or pass `--upload-root-template` on the command line to ensure root (and nested if being used) templates are uploaded to S3 first. You'll also need the `nesting_bucket` config set and appropriate permissions in place.

Hope that helps.

**Comment by pieter-vanisacker** [comment]
Great, that seems to have done the trick and upload the files through S3!
