### ISSUE TITLE
Issue with VPC peering connection...

### ISSUE THREAD

**Issue by ckuttruff** [sparkleformation/sfn#276]
Hey Chris!  Thanks for all your work on this project.  Had a great time setting things up for some infra we'll be managing.  I did run across one issue; not sure if this is related to sfn specifically, but maybe you could shed some light on it...

I am seeing the following error when trying to generate a vpc connection to a heroku vpc (in their new private spaces) and see the following:
``` 
User <user-id> cannot accept peering pcx-<pcx-id>                   
2018-04-26 03:41:08 UTC   my-staging               CREATE_FAILED        The following resource(s) failed to create: [MyVpcPeeringConnection].
```

I have `capabilities ['CAPABILITY_NAMED_IAM'] `  set in my .sfn config. and the dynamic block looks like this:
```
  dynamic!(:vpc_peering_connection, :my) do
    #depends_on!(:etison_iam_role)                                                                                                                

    properties do
      vpc_id ref!(:my_vpc)
      peer_vpc_id ref!(:heroku_vpc_id)
      peer_owner_id ref!(:heroku_aws_account_id)                                                                                                 
    end
  end
```

When I run the aws cli command to establish the VPC peering connection, it works fine with the same vpc / peer vpc info.  aws cli is configured with same environment variables for same aws keys.

Seemed a little similar to this issue:
https://github.com/sparkleformation/sfn/issues/225

I also tried to create a role with policies defined and then specify the PeerRoleArn as well in the properties block; also to no avail (diff error though: `API: ec2:AcceptVpcPeeringConnection Not authorized to perform
 sts:AssumeRole `).  This was according to a response on this SO thread: https://stackoverflow.com/a/45672210/1566623

Not sure if I have something basic misconfigured here, but stack / resource creation works up until the point of the vpc connection (creates vpc, internet gateway, etc just fine, so basic authentication seems to be succeeding).

Please let me know if I can provide any other information that would be helpful.  This is on latest version `3.0.30`.

Thanks again for all your work on this and related projects.  It's really nice to work with.

**Comment by ckuttruff** [comment]
Sorry, originally filed here:
https://github.com/sparkleformation/sparkle_formation/issues/242

**Comment by ckuttruff** [comment]
Oh, also definitely tried adding the `merge_api_options true` that was mentioned on other thread with @slyness

**Comment by ckuttruff** [comment]
I have spoken with AWS support and have tracked down the issue at play here.  Creating an AWS vpc peering connection via the aws CLI works fine in that the request is made from the outside account to the other vpc (heroku's in this case), and then the request shows as pending in the heroku CLI.  All good.

But how cloudformation handles this is it needs to complete the vpc connection entirely to show a COMPLETE status for the vpc peering connection creation.  Thus it needs the PeerRoleArn specified for the account that needs to accept the request.  The critical bit I was misunderstanding... this needs to be created with the accepter's account creds, not the initiating one (obvious when you know what cfn is actually attempting to do).  There are some docs on this scenario but I got a bit confused in here:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/peer-with-vpc-in-another-account.html

So for this scenario, this issue is kinda relevant:
https://github.com/sparkleformation/sfn-parameters/issues/15
Cause there are two different AWS accounts / creds to juggle here... in order to successfully this vpc peering.

Would love folks' thoughts about the use cases here for sfn supporting multiple AWS accounts.  How much of a lift would this be?  Happy to help with implementation there if I can...

**Comment by chrisroberts** [comment]
Hi! Glad that you got this worked out and thanks so much for leaving such a detailed reply here on the root cause. I'm sure at some point in the future you will save someone a headache trying to figure out what is going on. :smiley: 

Cheers!
