### ISSUE TITLE
sfn does not accept multiple values on the command line.

### ISSUE THREAD

**Issue by togacy** [sparkleformation/sfn#283]
Although :multiple is set to true in compile_time_parameters, multiple values can not be obtained with  sfn's command line option.

```
  :compile_time_parameters => {
    :allowed_regions => {
      :type => :string,
      :multiple => true,
      :default => ''
    }
  }
```

sfn like bellow.

```
 sfn create initial-settings \
  --file initialize_account \
  --no-interactive-parameters \
  --compile-parameters allowed_regions:"us-east-1,ap-northeast-1"
```
Only us-east-1 is set to :allowed_regions.  
The cli delimiter seems to be valid even if it is enclosed by double quotation.  
  
Both are set for interactive input.

```
[Sfn]: AllowedRegions: us-east-1,ap-northeast-1
```

**Comment by chrisroberts** [comment]
@togacy This will be fixed in the next release via #287. You'll be able to set multiple values by defining the key multiple times. For example:

```
--compile-parameters "allowed_regions=us-east-1,allowed_regions=ap-northeast-1"
```

Thanks so much for reporting this issue!
