### ISSUE TITLE
ERROR: TypeError: no implicit conversion of nil into String after adding --upload-root-template

### ISSUE THREAD

**Issue by bsushant-athena** [sparkleformation/sfn#294]
Hi,

ERROR: TypeError: no implicit conversion of nil into String after adding "--upload-root-template"
Can someone please help me with this?

Thanks,
Sushant

**Comment by chrisroberts** [comment]
Hi! This is most likely due to the remote bucket name not being set within the .sfn configuration file. I will look at why a nicer error message isn't being generated and fix that up.

Cheers

**Comment by bsushant-athena** [comment]
@chrisroberts What name shall I add in .sfn config file?

**Comment by lauraglasu** [comment]
You need to add the name of a bucket that you have permissions to write into

**Comment by bsushant-athena** [comment]
thanks, it worked 👍

**Comment by chrisroberts** [comment]
Added option value check and output error indicating missing option in v3.1.6
