### ISSUE TITLE
sfn does respect multiple:true for apply-stack

### ISSUE THREAD

**Issue by JonathanSerafini** [sparkleformation/sfn#7]
It appears that multiple calls to --apply-stack only preserves the last value specified. Looking at the options hash in bogo-cli's init, it looks like it's only receiving a string value. 

So given `stack create --apply-stack vpc --apply-stack app-base app-specific`, you'd only inherit the outputs from *app-base* and not from *vpc*. 

The attribute appears to be defined with multiple: true which would indicate that it supports more than one :(

**Comment by chrisroberts** [comment]
Looks like I had updated to constructing the options, but hadn't actually used those constructed options when setting up the flag. That change should make things correct.

**Comment by JonathanSerafini** [comment]
Oh, that may explain it. 
Unfortunately that last commit seems to break loading templates from ask_question ( with -f it works ) and apply_stack is still a single string in the config hash.

**Comment by chrisroberts** [comment]
:+1:, `Hash` explicitly required since symbol keys are required for setup. Last two commits fix up the apply and the file prompt.

**Comment by JonathanSerafini** [comment]
That did the trick, thanks !

**Comment by chrisroberts** [comment]
Fix released in 0.3.6. Thanks for reporting this and giving the fix a spin!

**Comment by mg03** [comment]
Hi

Im on version 0.4.10 and im seeing the behavior wherein only the last apply-stack value is being respected irrespective of whether i use a -f flag or not. Any help would be appreciated? 

regards
