### ISSUE TITLE
Miasma::Error::ApiError with sfn 0.3.6 and latest around of miasma upgrades

### ISSUE THREAD

**Issue by JonathanSerafini** [sparkleformation/sfn#8]
Attempting to create a stack within the latest sfn changes returns the error listed below whereas the same stack creates successfully on sfn 0.3.5 : 

ERROR: Miasma::Error::ApiError::RequestError: Bad Request - ValidationError: 1 validation error detected: Value 'nothing' at 'onFailure' failed to satisfy constraint: Member must satisfy enum value set: [ROLLBACK, DELETE, DO_NOTHING]

I swear I don't mean to find these :D

**Comment by chrisroberts** [comment]
Hi! It was a bad mapping on the disable rollback to on failure mapping. Fix has been pushed into the miasma-aws gem so a bundle update should get things fixed up. Thanks again for finding it and the report!
