### ISSUE TITLE
Parameter only updates do not affect resources

### ISSUE THREAD

**Issue by luckymike** [sparkleformation/sfn#83]
Since planning, parameter only updates that should trigger resource changes don't work. I need to pass `--file` and a template to pick them up.

The parameter is updated correctly, but that change is not reflected in the build resources.

**Comment by luckymike** [comment]
I've now observed this behavior with both nested stacks and single stacks. Hard to say if this is actually related to the planning changes, or if a CFN API change just happened to coincide with planning.

**Comment by chrisroberts** [comment]
Fixed via #85 and released
