### ISSUE TITLE
sfn stack deployment failures return success

### ISSUE THREAD

**Issue by JonathanSerafini** [sparkleformation/sfn#9]
Sfn will return a green success message even when an sfn update has failed and been rolled back.

Not entirely sure whether this is a bug. This may very well be due to the auto-rollback functionality, and may theoretically be "valid", but it does affect convenience / usability. Ideally this should return either an Error or a Warning depending on which side of the fence you're on.

**Comment by chrisroberts** [comment]
https://github.com/sparkleformation/sfn/issues/3 but on `update`

**Comment by chrisroberts** [comment]
This is fixed in 0.3.8. Thanks!
