### ISSUE TITLE
New resources created via stack update aren't shown in stack output

### ISSUE THREAD

**Issue by luckymike** [sparkleformation/sfn#91]
New resources created by adjusting compile time parameters (specifically adding subnets for additional AZs) are created but not shown at the end of the update events poll.

The resources are visible via stack inspection & `describe -o`, and they are properly detected with an `--apply-stack`, they just aren't shown in the automatic outputs.

**Comment by chrisroberts** [comment]
Due to stack data model being previously initialized resulting in cached outputs used during describe transition after successful update. Needs a clear run prior to output fetch.

**Comment by chrisroberts** [comment]
Forced resource collection reload prior to `describe` added.
